  - name: Install system dependencies
    run: |
      sudo apt-get update
      sudo apt-get install -y \
        build-essential \
        python3 \
        libc6-dev \
        libglib2.0-0 \
        libnss3 \
        libx11-xcb1 \
        libxcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxtst6

  - name: Build for Chrome
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    run: |
      echo "--- Memory Before Build ---"
      free -m
      
      echo "--- Starting Build ---"
      strace -f -o strace_output.txt pnpm build
      
      echo "--- Memory After Build ---"
      free -m
      BUILD_EXIT_CODE=$?
      echo "--- strace output ---"
      cat strace_output.txt || echo "No strace output"
      exit $BUILD_EXIT_CODE
      # ... rest of existing build commands ... 